"""add team roster and stats fields

Revision ID: 71d9910f0f3f
Revises: 5a1948a649b5
Create Date: 2026-09-09 21:22:40.135388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d9910f0f3f'
down_revision: Union[str, Sequence[str], None] = '5a1948a649b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team_id', sa.BigInteger(), nullable=True))
    op.add_column('players', sa.Column('position', sa.String(), nullable=True))
    op.add_column('players', sa.Column('points_per_game', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('rebounds_per_game', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('assists_per_game', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('stats_synced_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['id'])
    op.add_column('teams', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('losses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'losses')
    op.drop_column('teams', 'wins')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'stats_synced_at')
    op.drop_column('players', 'assists_per_game')
    op.drop_column('players', 'rebounds_per_game')
    op.drop_column('players', 'points_per_game')
    op.drop_column('players', 'position')
    op.drop_column('players', 'team_id')
    # ### end Alembic commands ###
